;;;; Screamer
;;;; A portable efficient implementation of nondeterministic Common Lisp
;;;;
;;;; Written by:
;;;;
;;;;   Jeffrey Mark Siskind (Department of Computer Science, University of Toronto)
;;;;   David Allen McAllester (MIT Artificial Intelligence Laboratory)
;;;;
;;;; Copyright 1991 Massachusetts Institute of Technology. All rights reserved.
;;;; Copyright 1992, 1993 University of Pennsylvania. All rights reserved.
;;;; Copyright 1993 University of Toronto. All rights reserved.
;;;;
;;;; Permission is hereby granted, free of charge, to any person obtaining a copy of
;;;; this software and associated documentation files (the "Software"), to deal in
;;;; the Software without restriction, including without limitation the rights to
;;;; use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
;;;; the Software, and to permit persons to whom the Software is furnished to do so,
;;;; subject to the following conditions:
;;;;
;;;; The above copyright and authorship notice and this permission notice shall be
;;;; included in all copies or substantial portions of the Software.
;;;;
;;;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
;;;; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
;;;; FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
;;;; COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
;;;; IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
;;;; CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

(defpackage #:screamer-system (:use #:asdf #:cl))
(in-package #:screamer-system)

(defclass file-warn-only (cl-source-file) ())

(defmethod perform :around ((op compile-op) (c file-warn-only))
  (setf (operation-on-failure op) :warn)
  (call-next-method))

(defsystem :screamer-tests
  :depends-on (:screamer :hu.dwim.stefil)
  :components
    ((:file "iterate")
     (:file "primordial" :depends-on ("iterate" "screamer"))
     ;;Permit four Duplicate definition warnings generated by SBCL
     (file-warn-only "screams" :depends-on ("iterate" "screamer"))
     (:file "equations" :depends-on ("iterate" "screamer"))
     (:file "tests"))
  :perform (compile-op :after (op c)
		       (print (funcall (intern
					"PRIME-ORDEAL" "PRIMORDIAL")))))
